python validation.py \
--load_name './models/EMPC_epoch40_bs64.pth' \
--batch_size 1 \
--num_workers 1 \
--pad 'zero' \
--activ 'relu' \
--norm 'bn' \
--baseroot_rgb './dataset/ILSVRC2012_val_256' \
--crop_size 256 \
